var CANVAS_WIDTH = 1360,
  CANVAS_HEIGHT = 640,
  CANVAS_WIDTH_HALF = 0.5 * CANVAS_WIDTH,
  CANVAS_HEIGHT_HALF = 0.5 * CANVAS_HEIGHT,
  EDGEBOARD_X = 250,
  EDGEBOARD_Y = 20,
  DISABLE_SOUND_MOBILE = 1,
  FONT_GAME = 'blackplotanregular',
  SECONDARY_FONT = 'blackplotanregular',
  FPS = 30,
  FPS_DESKTOP = 60,
  FPS_TIME = 1 / FPS,
  ROLL_BALL_RATE = 60 / FPS,
  STATE_LOADING = 0,
  STATE_MENU = 1,
  STATE_HELP = 1,
  STATE_GAME = 3,
  ON_MOUSE_DOWN = 0,
  ON_MOUSE_UP = 1,
  ON_MOUSE_OVER = 2,
  ON_MOUSE_OUT = 3,
  ON_DRAG_START = 4,
  ON_DRAG_END = 5,
  ON_TWEEN_ENDED = 6,
  ON_BUT_NO_DOWN = 7,
  ON_BUT_YES_DOWN = 8,
  STEP_RATE = 1.5,
  TEXT_SIZE = [80, 100, 130],
  LOCAL_BEST_SCORE = 0,
  START_HAND_SWIPE_POS = { x: CANVAS_WIDTH_HALF, y: CANVAS_HEIGHT_HALF + 200 },
  END_HAND_SWIPE_POS = [
    { x: CANVAS_WIDTH_HALF - 250, y: CANVAS_HEIGHT_HALF - 200 },
    { x: CANVAS_WIDTH_HALF, y: CANVAS_HEIGHT_HALF - 200 },
    { x: CANVAS_WIDTH_HALF + 250, y: CANVAS_HEIGHT_HALF - 200 },
  ],
  MS_TIME_SWIPE_END = 1e3,
  MS_TIME_SWIPE_START = 3e3,
  MS_TIME_FADE_HELP_TEXT = 500,
  LOCALSTORAGE_STRING = ['penalty_best_score'],
  TEXT_EXCELLENT_COLOR = ['#fff', '#5d96fe'],
  TEXT_COLOR = '#ffffff',
  TEXT_COLOR_1 = '#ff2222',
  TEXT_COLOR_STROKE = '#002a59',
  OUTLINE_WIDTH = 1.5,
  TIME_INTERVAL_STROBE = 0.2,
  PHYSICS_ACCURACY = 3,
  MOBILE_OFFSET_GLOVES_X = -100,
  BALL_VELOCITY_MULTIPLIER = 1,
  PHYSICS_STEP = 1 / (FPS * STEP_RATE),
  MS_WAIT_SHOW_GAME_OVER_PANEL = 250,
  STATE_INIT = 0,
  STATE_PLAY = 1,
  STATE_FINISH = 2,
  STATE_PAUSE = 3,
  IDLE = 0,
  RIGHT = 1,
  LEFT = 2,
  CENTER_DOWN = 3,
  CENTER_UP = 4,
  LEFT_DOWN = 5,
  RIGHT_DOWN = 6,
  ANIM_GOAL_KEEPER_FAIL = [LEFT, RIGHT, CENTER_DOWN, CENTER_UP, LEFT_DOWN, RIGHT_DOWN],
  ANIM_GOAL_KEEPER_FAIL_ALT = [LEFT, RIGHT, LEFT_DOWN, RIGHT_DOWN],
  NUM_SPRITE_PLAYER = 31,
  SPRITE_NAME_GOALKEEPER = 'gk_idle_ gk_save_right_ gk_save_left_ gk_save_center_down_ gk_save_center_up_ gk_save_down_left_ gk_save_down_right'.split(
    ' ',
  ),
  NUM_SPRITE_GOALKEEPER = [24, 34, 34, 51, 25, 34, 34],
  OFFSET_CONTAINER_GOALKEEPER = [
    { x: 0, y: 0 },
    { x: 15, y: -29 },
    { x: -360, y: -29 },
    { x: -15, y: -15 },
    { x: -20, y: -85 },
    { x: -355, y: 20 },
    { x: 21, y: 20 },
  ],
  BALL_MASS = 0.5,
  BALL_RADIUS = 0.64,
  BALL_LINEAR_DAMPING = 0.2,
  OBJECT,
  TIME_TRY_TO_SHOT_BALL_OPPONENT = 0.7,
  START_POS_FLAG = { x: 277, y: 268 },
  FLAG_ADDED_POS = { x: 61, y: 69 },
  FLAG_LIMIT_POS_X = 690,
  TOT_TEAM = 32,
  MIN_BALL_VEL_ROTATION = 0.1,
  TIME_RESET_AFTER_GOAL = 1e3,
  SHOOT_FRAME = 7,
  HAND_KEEPER_ANGLE_RATE = 0.15,
  TIME_POLE_COLLISION_RESET = 1e3,
  LIMIT_HAND_RANGE_POS = {
    x: 16.8,
    zMax: 3.1,
    zMin: -8.5,
  },
  BACK_WALL_GOAL_SIZE = { width: 20.5, depth: 1, height: 7.5 },
  LEFT_RIGHT_WALL_GOAL_SIZE = { width: 0.1, depth: 25, height: 7.5 },
  UP_WALL_GOAL_SIZE = { width: 20.5, depth: 25, height: 0.1 },
  BACK_WALL_GOAL_POSITION = { x: 0, y: 155, z: -2.7 },
  GOAL_LINE_POS = {
    x: 0,
    y: BACK_WALL_GOAL_POSITION.y - UP_WALL_GOAL_SIZE.depth + 2,
    z: BACK_WALL_GOAL_POSITION.z,
  },
  POSITION_BALL = { x: 0.05, y: 15.4, z: -9 + BALL_RADIUS },
  NUM_AREA_GOAL = { h: 3, w: 5 },
  AREA_GOALS_ANIM = [
    LEFT,
    LEFT,
    CENTER_UP,
    RIGHT,
    RIGHT,
    LEFT,
    LEFT,
    CENTER_UP,
    RIGHT,
    RIGHT,
    LEFT_DOWN,
    LEFT_DOWN,
    CENTER_DOWN,
    RIGHT_DOWN,
    RIGHT_DOWN,
  ],
  GOAL_SPRITE_SWAP_Y = GOAL_LINE_POS.y,
  GOAL_SPRITE_SWAP_Z = BACK_WALL_GOAL_POSITION.z + LEFT_RIGHT_WALL_GOAL_SIZE.height,
  BALL_OUT_Y = BACK_WALL_GOAL_POSITION.y + 3,
  BUFFER_ANIM_PLAYER = FPS,
  MS_EFFECT_ADD = 1500,
  MS_ROLLING_SCORE = 500,
  MAX_PERCENT_PROBABILITY = 100,
  GOAL_KEEPER_TOLLERANCE_LEFT = -4,
  GOAL_KEEPER_TOLLERANCE_RIGHT = 4,
  TIME_RESET_AFTER_BALL_OUT = 250,
  TIME_RESET_AFTER_SAVE = 500,
  AREA_GOAL_PROPERTIES = { width: 4, depth: 1, height: 2.4 },
  FIRST_AREA_GOAL_POS = {
    x: -14 - 0.5 * AREA_GOAL_PROPERTIES.width,
    y: BACK_WALL_GOAL_POSITION.y - UP_WALL_GOAL_SIZE.depth + 1.1,
    z: 3.1 - 0.5 * AREA_GOAL_PROPERTIES.height,
  },
  GOAL_KEEPER_DEPTH_Y = BACK_WALL_GOAL_POSITION.y - UP_WALL_GOAL_SIZE.depth,
  POLE_UP_SIZE = {
    radius_top: 0.5,
    radius_bottom: 0.5,
    height: 40.5,
    segments: 10,
  },
  POLE_RIGHT_LEFT_SIZE = {
    radius_top: 0.5,
    radius_bottom: 0.5,
    height: 15,
    segments: 10,
  },
  COLOR_AREA_GOAL = [
    16711680,
    65280,
    255,
    16776960,
    16711935,
    65535,
    15790320,
    986895,
    16759705,
    16777215,
    5675280,
    10083618,
    1056896,
    8392736,
    9017449,
  ],
  OFFSET_FIELD_Y = 35,
  OFFSET_FIELD_X = 35,
  HIT_BALL_MAX_FORCE = 130,
  HIT_BALL_MIN_FORCE = 5,
  FORCE_RATE = 0.0014,
  SHOW_AREAS_GOAL = !1,
  FORCE_MULTIPLIER_AXIS = { x: 0.12, y: 0.4, z: 0.08 },
  FORCE_MAX = 0.5,
  FIELD_POSITION,
  MAX_FORCE_Y = 66,
  MIN_FORCE_Y = 50,
  CALCULATE_PROBABILITY = [
    { xMax: -7, xMin: -11, zMax: 11, zMin: 8 },
    { xMax: -3.6, xMin: -7, zMax: 11, zMin: 8 },
    { xMax: 3.6, xMin: -3.6, zMax: 11, zMin: 8 },
    { xMax: 7, xMin: 3.6, zMax: 11, zMin: 8 },
    { xMax: 11, xMin: 7, zMax: 11, zMin: 8 },
    { xMax: -7, xMin: -7, zMax: 8, zMin: 5 },
    { xMax: -3.6, xMin: -7, zMax: 8, zMin: 5 },
    { xMax: 3.6, xMin: -3.6, zMax: 8, zMin: 5 },
    { xMax: 7, xMin: 3.6, zMax: 8, zMin: 5 },
    { xMax: 11, xMin: 7, zMax: 8, zMin: 5 },
    {
      xMax: -7,
      xMin: -11,
      zMax: 5,
      zMin: 0,
    },
    { xMax: -3.6, xMin: -7, zMax: 5, zMin: 0 },
    { xMax: 3.6, xMin: -3.6, zMax: 5, zMin: 0 },
    { xMax: 7, xMin: 3.6, zMax: 5, zMin: 0 },
    { xMax: 11, xMin: 7, zMax: 5, zMin: 0 },
  ],
  SHOW_3D_RENDER = !1,
  CAMERA_TEST_TRACKBALL = !1,
  CAMERA_TEST_TRANSFORM = !1,
  CANVAS_3D_OPACITY = 0.5,
  MOUSE_SENSIBILTY = 0.03,
  CAMERA_TEST_LOOK_AT = { x: 0, y: -500, z: -100 },
  BALL_SCALE_FACTOR = 0.07,
  SHADOWN_FACTOR = 1.1,
  INTENSITY_DISPLAY_SHOCK = [
    { x: 10, y: 7.5, time: 50 },
    { x: 20, y: 9, time: 50 },
    { x: 30, y: 12, time: 50 },
    { x: 33, y: 15, time: 50 },
  ],
  FORCE_BALL_DISPLAY_SHOCK = [
    { max: 55, min: MIN_FORCE_Y - 1 },
    { max: 58, min: 55 },
    { max: 62, min: 58 },
    { max: MAX_FORCE_Y, min: 62 },
  ],
  CAMERA_POSITION = { x: 0, y: 0, z: -7 },
  FOV = 15,
  NEAR = 1,
  FAR = 2e3,
  ENABLE_FULLSCREEN,
  ENABLE_CHECK_ORIENTATION,
  TIME_SWIPE
